### ISSUE TITLE
Latest gem release 0.4.0 doesn't get installed

### ISSUE THREAD

**Issue by alfred-rp** [gary-rafferty/perfecta#8]
The latest gem release v0.4.0 does't get installed in a rails 4.2.1 app because of activesupport dependency for this gem.

But works fine with the latest master.

@gary-rafferty Could you possibly release a new gem version which could fix this. So that i won't have to point to a github link in my gemfile

**Comment by gary-rafferty** [comment]
Thanks for letting me know @alfred-rp - Ive just pushed a [new version](https://rubygems.org/gems/perfecta/versions/0.5.0) to Rubygems.
Please do let me know if issue remains.

**Comment by alfred-rp** [comment]
Nop the issue is resolved. Thanks :)
